### ISSUE TITLE
how to building and run it?

### ISSUE THREAD

**Issue by andyyuan78** [piantado/GPUropolis#1]
ubgpu@ubgpu:~/github/GPUropolis$ make
nvcc -m64 -gencode arch=compute_30,code=sm_30 -use_fast_math -I/usr/local/cuda/lib64  -I. -I/usr/local/cuda/samples/common/inc/ -o main.o -c src/main.cu 
In file included from src/main.cu:18:0:
src/cuPrintf.cu:57:36: fatal error: sm_11_atomic_functions.h: No such file or directory
 #include <sm_11_atomic_functions.h>
                                    ^
compilation terminated.
make: **\* [main.o] Error 1
ubgpu@ubgpu:~/github/GPUropolis$ 
ubgpu@ubgpu:~/github/GPUropolis$ 

ubgpu@ubgpu:~/github/GPUropolis$ sudo bash run-all.sh
Running data-sources/Stats/Logistic
./gpumcmc: error while loading shared libraries: libcudart.so.5.0: cannot open shared object file: No such file or directory

real    0m0.002s
user    0m0.000s
sys     0m0.002s
sort: cannot read: ./run/data-sources/Stats/Logistic-all//samples.txt: No such file or directory
ubgpu@ubgpu:~/github/GPUropolis$

**Comment by piantado** [comment]
Sorry, but this project is pretty defunct. You might be able to extract something useful from the code itself, but nothing is being maintained or further developed. (Actually, the entire idea didn't work well--email me if you'd like the details!)
